spring:
  profiles:
    # 默认测试环境 dev
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB # 限制单个上传文件的最大大小为 10MB。如果上传的文件大小超过这个值，将会被拒绝上传。
      max-request-size: 10MB # 限制整个上传请求的最大大小为 10MB。这包括所有上传文件的大小之和。如果请求总大小超过这个值，将会被拒绝。
jwt:
    issuer: quanxiaoha
    secret: HgtHeHCKtSlyERcYEkmxjIBHy2Ii7VdXOahtihT+Q89/pie6bqvwpzlypIb83uRqjjpHuWkDCb1iPGak3Lp6rw==
    tokenExpireTime: 1440
  # token 请求头中的 key 值
    tokenHeaderKey: Authorization
  # token 请求头中的 value 值前缀
    tokenPrefix: Bearer
