package com.oiazheng.weblog.common.enums;

import com.oiazheng.weblog.common.exception.BaseExceptionInterface;
import lombok.AllArgsConstructor;
import lombok.Getter;


@Getter
@AllArgsConstructor
public enum ResponseCodeEnum implements BaseExceptionInterface {
    // ------------------- 通用异常状态码 -------------------
    SYSTEM_ERROR("10000", "出错啦~页面小哥正在努力修复中哦..."),

    // ------------------- 业务异常状态码 -------------------
    PRODUCT_NOT_FOUND("20000", "商品不存在(TEXTING)"),

    PARAM_NOT_VALID("10001", "参数错误"),

    LOGIN_FAIL("20000", "登录失败"),

    USERNAME_OR_PWD_ERROR("20001", "用户名或密码错误"),

    UNAUTHORIZED("20002", "无访问权限，请先登录！"),

    FORBIDDEN("20004", "演示账号仅支持查询操作！"),
    USERNAME_NOT_FOUND("20003", "该用户不存在"),
    CATEGORY_NAME_IS_EXISTED("20005", "该分类已存在，请勿重复添加！"),
    TAG_CANT_DUPLICATE("20006", "该标签已存在，请勿重复添加！"),
    TAG_NOT_EXISTED("20007", "该标签不存在!"),
    FILE_UPLOAD_FAILED("20008", "文件上传失败！"),
    CATEGORY_NOT_EXISTED("20009", "提交的分类不存在！"),
    ARTICLE_NOT_FOUND("20010", "该文章不存在！"),
    CATEGORY_CAN_NOT_DELETE("20011", "该分类下包含文章，请先删除对应文章，才能删除！"),
    TAG_CAN_NOT_DELETE("20012", "该标签下包含文章，请先删除对应文章，才能删除！"),
    ARTICLE_CAN_NOT_DELETE("20013", "该文章已发布，请先撤回或删除！"),
    ARTICLE_IS_PUBLISHED("20014", "该文章已发布，请勿重复发布！"),
    ARTICLE_IS_DRAFT("20015", "该文章未发布，请先发布！"),
    ARTICLE_IS_DELETED("20016", "该文章已删除，请勿重复删除！"),
    ARTICLE_IS_NOT_DELETED("20017", "该文章未删除，请先删除！"),
    ARTICLE_IS_REVERTED("20018", "该文章已撤回，请勿重复撤回！"),
    ARTICLE_IS_NOT_REVERTED("20019", "该文章未撤回，请先撤回！"),
    ARTICLE_IS_DRAFT_OR_REVERTED("20020", "该文章已发布或已撤回，请勿重复操作！"),
    ARTICLE_IS_PUBLISHED_OR_DELETED("20021", "该文章已发布或已删除，请勿重复操作！"),
    ARTICLE_IS_DRAFT_OR_DELETED("20022", "该文章未发布或已删除，请先发布或删除！"),
    ARTICLE_IS_DRAFT_OR_REVERTED_OR_DELETED("20023", "该文章已发布或已撤回或已删除，请勿重复操作！"),
    ARTICLE_IS_PUBLISHED_OR_REVERTED("20024", "该文章已发布或已撤回，请勿重复操作！"),
    ARTICLE_IS_PUBLISHED_OR_DELETED_OR_REVERTED("20025", "该文章已发布或已删除或已撤回，请勿重复操作！"),
    ARTICLE_IS_DRAFT_OR_PUBLISHED_OR_REVERTED("20026", "该文章未发布或已发布或已撤回，请先发布或撤回！"),
    ARTICLE_IS_DRAFT_OR_PUBLISHED_OR_DELETED("20027", "该文章未发布或已发布或已删除，请先发布或删除！"),
    ARTICLE_IS_DRAFT_OR_PUBLISHED_OR_DELETED_OR_REVERTED("20028", "该文章未发布或已发布或已删除或已撤回，请先发布或撤回或删除！"),
    ARTICLE_IS_DRAFT_OR_PUBLISHED_OR_DELETED_OR_REVERTED_OR_DELETED("20029", "该文章已发布或已撤回或已删除，请勿重复操作！"),
    ARTICLE_IS_DRAFT_OR_PUBLISHED_OR_DELETED_OR_REVERTED_OR_DELETED_OR_LOCKED("20030", "该文章已发布或已撤回或已删除，请勿重复操作！"),
    ARTICLE_IS_DRAFT_OR_PUBLISHED_OR_DELETED_OR_REVERTED_OR_DELETED_OR_LOCKED_OR_UNLOCKED("20031", "该文章已发布或已撤回或已删除，请勿重复操作！"),
    ARTICLE_IS_DRAFT_OR_PUBLISHED_OR_DELETED_OR_REVERTED_OR_DELETED_OR_LOCKED_OR_UNLOCKED_OR_ARCHIVED("20032", "该文章已发布或已撤回或已删除，请勿重复操作！"),
    ARTICLE_IS_DRAFT_OR_PUBLISHED_OR_DELETED_OR_REVERTED_OR_DELETED_OR_LOCKED_OR_UNLOCKED_OR_ARCHIVED_OR_RESTORED("20033", "该文章已发布或已撤回或已删除，请勿重复操作！"),
    ARTICLE_IS_DRAFT_OR_PUBLISHED_OR_DELETED_OR_REVERTED_OR_DELETED_OR_LOCKED_OR_UNLOCKED_OR_ARCHIVED_OR_RESTORED_OR_UNARCHIVED("20034", "该文章已发布或已撤回或已删除，请勿重复操作！"),
    ARTICLE_IS_DRAFT_OR_PUBLISHED_OR_DELETED_OR_REVERTED_OR_DELETED_OR_LOCKED_OR_UNLOCKED_OR_ARCHIVED_OR_RESTORED_OR_UNARCHIVED_OR_PINNED("20035", "该文章已发布或已撤回或已删除，请勿重复操作！"),
    ARTICLE_IS_DRAFT_OR_PUBLISHED_OR_DELETED_OR_REVERTED_OR_DELETED_OR_LOCKED_OR_UNLOCKED_OR_ARCHIVED_OR_RESTORED_OR_UNARCHIVED_OR_PINNED_OR_UNPINNED("20036", "该文章已发布或已撤回或已删除，请勿重复操作！"),
    ARTICLE_IS_DRAFT_OR_PUBLISHED_OR_DELETED_OR_REVERTED_OR_DELETED_OR_LOCKED_OR_UNLOCKED_OR_ARCHIVED_OR_RESTORED_OR_UNARCHIVED_OR_PINNED_OR_UNPINNED_OR_HIDDEN("20037", "该文章已发布或已撤回或已删除，请勿重复操作！"),
    ARTICLE_IS_DRAFT_OR_PUBLISHED_OR_DELETED_OR_REVERTED_OR_DELETED_OR_LOCKED_OR_UNLOCKED_OR_ARCHIVED_OR_RESTORED_OR_UNARCHIVED_OR_PINNED_OR_UNPINNED_OR_HIDDEN_OR_VISIBLE("20038", "该文章已发布或已撤回或已删除，请勿重复操作！"),
    ARTICLE_IS_DRAFT_OR_PUBLISHED_OR_DELETED_OR_REVERTED_OR_DELETED_OR_LOCKED_OR_UNLOCKED_OR_ARCHIVED_OR_RESTORED_OR_UNARCHIVED_OR_PINNED_OR_UNPINNED_OR_HIDDEN_OR_VISIBLE_OR_STARRED("20039", "该文章已发布或已撤回或已删除，请勿重复操作！"),
    ARTICLE_IS_DRAFT_OR_PUBLISHED_OR_DELETED_OR_REVERTED_OR_DELETED_OR_LOCKED_OR_UNLOCKED_OR_ARCHIVED_OR_RESTORED_OR_UNARCHIVED_OR_PINNED_OR_UNPINNED_OR_HIDDEN_OR_VISIBLE_OR_STARRED_OR_UNSTARRED("20040", "该文章已发布或已撤回或已删除，请勿重复操作！"),
    ARTICLE_IS_DRAFT_OR_PUBLISHED_OR_DELETED_OR_REVERTED_OR_DELETED_OR_LOCKED_OR_UNLOCKED_OR_ARCHIVED_OR_RESTORED_OR_UNARCHIVED_OR_PINNED_OR_UNPINNED_OR_HIDDEN_OR_VISIBLE_OR_STARRED_OR_UNSTARRED_OR_FAVORITE("20041", "该文章已发布或已撤回或已删除，请勿重复操作！"),
    ARTICLE_IS_DRAFT_OR_PUBLISHED_OR_DELETED_OR_REVERTED_OR_DELETED_OR_LOCKED_OR_UNLOCKED_OR_ARCHIVED_OR_RESTORED_OR_UNARCHIVED_OR_PINNED_OR_UNPINNED_OR_HIDDEN_OR_VISIBLE_OR_STARRED_OR_UNSTARRED_OR_FAVORITE_OR_UNFAVORITE("20042", "该文章已发布或已撤回或已删除，请勿重复操作！"),
    ARTICLE_IS_DRAFT_OR_PUBLISHED_OR_DELETED_OR_REVERTED_OR_DELETED_OR_LOCKED_OR_UNLOCKED_OR_ARCHIVED_OR_RESTORED_OR_UNARCHIVED_OR_PINNED_OR_UNPINNED_OR_HIDDEN_OR_VISIBLE_OR_STARRED_OR_UNSTARRED_OR_FAVORITE_OR_UNFAVORITE_OR_COMMENTED("20043", "该文章已发布或已撤回或已删除，请勿重复操作！"),
    ARTICLE_IS_DRAFT_OR_PUBLISHED_OR_DELETED_OR_REVERTED_OR_DELETED_OR_LOCKED_OR_UNLOCKED_OR_ARCHIVED_OR_RESTORED_OR_UNARCHIVED_OR_PINNED_OR_UNPINNED_OR_HIDDEN_OR_VISIBLE_OR_STARRED_OR_UNSTARRED_OR_FAVORITE_OR_UNFAVORITE_OR_COMMENTED_OR_UNCOMMENTED("20044", "该文章已发布或已撤回或已删除，请勿重复操作！"),
    ARTICLE_IS_DRAFT_OR_PUBLISHED_OR_DELETED_OR_REVERTED_OR_DELETED_OR_LOCKED_OR_UNLOCKED_OR_ARCHIVED_OR_RESTORED_OR_UNARCHIVED_OR_PINNED_OR_UNPINNED_OR_HIDDEN_OR_VISIBLE_OR_STARRED_OR_UNSTARRED_OR_FAVORITE_OR_UNFAVORITE_OR_COMMENTED_OR_UNCOMMENTED_OR_REPORTED("20045", "该文章已发布或已撤回或已删除，请勿重复操作！"),
    ARTICLE_IS_DRAFT_OR_PUBLISHED_OR_DELETED_OR_REVERTED_OR_DELETED_OR_LOCKED_OR_UNLOCKED_OR_ARCHIVED_OR_RESTORED_OR_UNARCHIVED_OR_PINNED_OR_UNPINNED_OR_HIDDEN_OR_VISIBLE_OR_STARRED_OR_UNSTARRED_OR_FAVORITE_OR_UNFAVORITE_OR_COMMENTED_OR_UNCOMMENTED_OR_REPORTED_OR_UNREPORTED("20046", "该文章已发布或已撤回或已删除，请勿重复操作！"),
    ARTICLE_IS_DRAFT_OR_PUBLISHED_OR_DELETED_OR_REVERTED_OR_DELETED_OR_LOCKED_OR_UNLOCKED_OR_ARCHIVED_OR_RESTORED_OR_UNARCHIVED_OR_PINNED_OR_UNPINNED_OR_HIDDEN_OR_VISIBLE_OR_STARRED_OR_UNSTARRED_OR_FAVORITE_OR_UNFAVORITE_OR_COMMENTED_OR_UNCOMMENTED_OR_REPORTED_OR_UNREPORTED_OR_READ("20047", "该文章已发布或已撤回或已删除，请勿重复操作！"),
    ARTICLE_IS_DRAFT_OR_PUBLISHED_OR_DELETED_OR_REVERTED_OR_DELETED_OR_LOCKED_OR_UNLOCKED_OR_ARCHIVED_OR_RESTORED_OR_UNARCHIVED_OR_PINNED_OR_UNPINNED_OR_HIDDEN_OR_VISIBLE_OR_STARRED_OR_UNSTARRED_OR_FAVORITE_OR_UNFAVORITE_OR_COMMENTED_OR_UNCOMMENTED_OR_REPORTED_OR_UNREPORTED_OR_READ_OR_UNREAD("20048", "该文章已发布或已撤回或已删除，请勿重复操作！"),
    ARTICLE_IS_DRAFT_OR_PUBLISHED_OR_DELETED_OR_REVERTED_OR_DELETED_OR_LOCKED_OR_UNLOCKED_OR_ARCHIVED_OR_RESTORED_OR_UNARCHIVED_OR_PINNED_OR_UNPINNED_OR_HIDDEN_OR_VISIBLE_OR_STARRED_OR_UNSTARRED_OR_FAVORITE_OR_UNFAVORITE_OR_COMMENTED_OR_UNCOMMENTED_OR_REPORTED_OR_UNREPORTED_OR_READ_OR_UNREAD_OR_BOOKMARKED("20049", "该文章已发布或已撤回或已删除，请勿重复操作！"),
    ARTICLE_IS_DRAFT_OR_PUBLISHED_OR_DELETED_OR_REVERTED_OR_DELETED_OR_LOCKED_OR_UNLOCKED_OR_ARCHIVED_OR_RESTORED_OR_UNARCHIVED_OR_PINNED_OR_UNPINNED_OR_HIDDEN_OR_VISIBLE_OR_STARRED_OR_UNSTARRED_OR_FAVORITE_OR_UNFAVORITE_OR_COMMENTED_OR_UNCOMMENTED_OR_REPORTED_OR_UNREPORTED_OR_READ_OR_UNREAD_OR_BOOKMARKED_OR_UNBOOKMARKED("20050", "该文章已发布或已撤回或已删除，请勿重复操作！"),
    ARTICLE_IS_DRAFT_OR_PUBLISHED_OR_DELETED_OR_REVERTED_OR_DELETED_OR_LOCKED_OR_UNLOCKED_OR_ARCHIVED_OR_RESTORED_OR_UNARCHIVED_OR_PINNED_OR_UNPINNED_OR_HIDDEN_OR_VISIBLE_OR_STARRED_OR_UNSTARRED_OR_FAVORITE_OR_UNFAVORITE_OR_COMMENTED_OR_UNCOMMENTED_OR_REPORTED_OR_UNREPORTED_OR_READ_OR_UNREAD_OR_BOOKMARKED_OR_UNBOOKMARKED_OR_SHARED("20051", "该文章已发布或已撤回或已删除，请勿重复操作！"),
    ARTICLE_IS_DRAFT_OR_PUBLISHED_OR_DELETED_OR_REVERTED_OR_DELETED_OR_LOCKED_OR_UNLOCKED_OR_ARCHIVED_OR_RESTORED_OR_UNARCHIVED_OR_PINNED_OR_UNPINNED_OR_HIDDEN_OR_VISIBLE_OR_STARRED_OR_UNSTARRED_OR_FAVORITE_OR_UNFAVORITE_OR_COMMENTED_OR_UNCOMMENTED_OR_REPORTED_OR_UNREPORTED_OR_READ_OR_UNREAD_OR_BOOKMARKED_OR_UNBOOKMARKED_OR_SHARED_OR_UNSHARED("20052", "该文章已发布或已撤回或已删除，请勿重复操作！"),

    ;
    // 异常码
    private String errorCode;
    // 错误信息
    private String errorMessage;



}
